{
 "title": "Translator Middleware",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Translations Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(translations_per_second{channel!=\"engine\"})",
     "legendFormat": "tps"
    }
   ]
  },
  {
   "title": "Translation Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(translation_error_rate{channel!=\"engine\"})",
     "legendFormat": "error_rate"
    }
   ]
  },
  {
   "title": "Translations Total (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(translations_total{channel!=\"engine\"}[1m]))",
     "legendFormat": "translations_rate"
    }
   ]
  }
 ]
}